---
title: "README.RMD"
author: "Huailin Tang"
date: "9/28/2021"
output: github_document
---

## Question 1

```{r echo=TRUE, message=FALSE, warning=FALSE}
library(dplyr)
library(nycflights13)
library(ggplot2)

sum(is.na(flights$dep_time))
print(head((flights[is.na(flights$dep_time),])))
```
In flights which have NA in dep_time, dep_delay, arr_time, arr_delay, air_time are also missing. The story might be these flights are cancelled. 

## Question 2

```{r message=FALSE, warning=FALSE}
head(mutate(flights,
       dep_time = (dep_time %/% 100) * 60 + (dep_time %% 100),
       sched_dep_time = (sched_dep_time %/% 100) * 60 + (sched_dep_time %% 100)))
```

## Question 3

```{r message=FALSE, warning=FALSE}
library(lubridate)
flights %>%
  mutate(dep_date = lubridate::make_datetime(year, month, day)) %>% group_by(dep_date) %>%
    summarise(cancelled = sum(is.na(dep_delay)), n = n(),
            mean_dep_delay = mean(dep_delay,na.rm=TRUE),
            mean_arr_delay = mean(arr_delay,na.rm=TRUE)) %>%
      ggplot(aes(x= cancelled/n)) + 
      geom_point(aes(y=mean_dep_delay), colour='blue', alpha=0.5) + geom_point(aes(y=mean_arr_delay), colour='red', alpha=0.5) + 
      xlab("proportion of cancelled flights") + ylab("delay time")
```
Generally there is no obvious relationship between proportion of cancelled flights and delay time. 

